import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import koneksimysql.koneksi;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Lenovo
 */
public class Halamaadmin extends javax.swing.JFrame {
private DefaultTableModel tabelsiswa;
koneksimysql.koneksi k = new koneksi();
 int index_baris;
  Connection con;
    /**
     * Creates new form Halamaadmin
     */
    public Halamaadmin() {
         initComponents();
        
        k.koneksi();
       
        
        
        tabelsiswa = new DefaultTableModel() ;
jTable1.setModel(tabelsiswa);

tabelsiswa.addColumn("NIS");
tabelsiswa.addColumn("Nama");
tabelsiswa.addColumn("Gender");
tabelsiswa.addColumn("Alamat");
tabelsiswa.addColumn("No HP");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txthp = new javax.swing.JTextField();
        txtnis = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtnama = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtalamat = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        txtgender = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, -1, 90));
        jPanel1.add(txthp, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 120, -1));
        jPanel1.add(txtnis, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 120, -1));

        jLabel1.setText("No HP");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, -1, -1));

        jLabel2.setText("NIS");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, -1));

        jLabel3.setText("Nama");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, -1));

        jLabel4.setText("Gender");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, -1));
        jPanel1.add(txtnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 120, -1));

        jLabel5.setText("Alamat");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, -1));
        jPanel1.add(txtalamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 120, -1));

        jButton1.setText("HAPUS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 280, -1, -1));

        jButton2.setText("SIMPAN");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, -1, -1));

        jButton3.setText("SIMPAN");
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, -1, -1));

        jButton4.setText("UBAH");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, -1, -1));

        jButton5.setText("LIHAT");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, -1, -1));

        txtgender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki-laki", "Perempuan" }));
        jPanel1.add(txtgender, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 100, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
            
            int r =jTable1.getSelectedRow();
            if (r != -1){
            int nis = Integer.parseInt(jTable1.getValueAt(r, 0).toString());
            String nama = jTable1.getValueAt(r, 1).toString();
            String gender = jTable1.getValueAt(r, 2).toString();
            String alamat = jTable1.getValueAt(r, 3).toString();
            String telp = jTable1.getValueAt(r, 4).toString();
            
            
            txtnama.setText(nama);
            txtgender.setSelectedItem(gender);
            txtalamat.setText(alamat);
            txthp.setText(telp);
            
           
              index_baris = r;}   // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
         try {
            k.stat.executeUpdate("insert into siswa values ("+"'"+txtnis.getText()+"',"
                + "'"+txtnama.getText()+"',"
                + "'"+txtgender.getSelectedItem()+"',"
                + "'"+txtalamat.getText()+"',"
                + "'"+txthp.getText()+"')");
            txtnis.setText("");
            txtnama.setText("");
            txtgender.setSelectedItem(" ");
            txtalamat.setText("");
            txthp.setText("");
            txtnis.requestFocus();
            JOptionPane.showMessageDialog(rootPane,"Data tersimpan");
        } catch (Exception e) {
        
          }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed


        // TODO add your handling code here:
        
        
        tabelsiswa.fireTableDataChanged();
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection connection = DriverManager.getConnection("jdbc:mysql://localhost/febri", "root", "");
            Statement statement = connection.createStatement();
            String sql = "select * from siswa order by nis";
            ResultSet rs = statement.executeQuery(sql);
            while (rs.next()){
                Object [] o = new Object[6];
                o[0] = rs.getString("nis");
                o[1] = rs.getString("nama");
                o[2] = rs.getString("gender");
                o[3] = rs.getString("alamat");
                o[4] = rs.getString("hp");
                

                tabelsiswa.addRow(o);

            }
            rs.close();
            statement.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Gagal koneksi "+e);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Halamaadmin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
              int pilihan = JOptionPane.showConfirmDialog(this, ""
            +"apa setuju dihapus", "komfirmasi",
            JOptionPane.YES_NO_CANCEL_OPTION);
        if (pilihan ==0) {
            tabelsiswa.removeRow(index_baris);
            refresh();
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
            
        if(txtnis.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Lengkapi data");
        }else{
        
         try{
             Class.forName("com.mysql.jdbc.Driver");
   Connection connection = DriverManager.getConnection("jdbc:mysql://localhost/febri", "root", "");
    Statement statement = connection.createStatement();
         String sql="UPDATE data set nama='"+txtnama.getText()+"',alamat='"+txtalamat.getText()+"',gender='"+txtgender.getSelectedItem()+"' WHERE nis='"+txtnis.getText()+"'";
         
        PreparedStatement ps=con.prepareStatement(sql);
        ps.executeUpdate();
        JOptionPane.showMessageDialog(null,"Berhasil Update Data");
        kosong();
     
       
    }catch(SQLException e){
         JOptionPane.showMessageDialog(this, "GAGAL \n"+e.getMessage());
    }    catch (ClassNotFoundException ex) {
             Logger.getLogger(Halamaadmin.class.getName()).log(Level.SEVERE, null, ex);
         }
         kosong();
      
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Halamaadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Halamaadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Halamaadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Halamaadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Halamaadmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtalamat;
    private javax.swing.JComboBox<String> txtgender;
    private javax.swing.JTextField txthp;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtnis;
    // End of variables declaration//GEN-END:variables
    private  void  refresh(){
        txtnis.setText("");
        txtgender.setSelectedItem(this);
        txtnama.setText("");
        txtalamat.setText("");
        txthp.setText("");

        jTable1.clearSelection();
    }
 private  void  kosong(){
        txtnis.setText(null);
        txtgender.setSelectedItem(this);
        txtnama.setText(null);
        txtalamat.setText(null);
        txthp.setText(null);

        jTable1.clearSelection();
    }
}
